---
title: "Grade analysis"
format: html
editor: visual
author: Yuntong Wu
---
Link to GitHub repository: https://github.com/wuyuntong/r-101-grade-analysis.

```{r, message=FALSE, warning=FALSE}
here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(knitr)
```

## Question 1
```{r}
grades <- vroom(here("grades.csv"))
```


## Question 2
```{r}
grades |>
  summarise("max grade" = max(Exam, na.rm = TRUE), "min grade" = min(Exam, na.rm = TRUE), "median grade" = median(Exam, na.rm = TRUE), "mean grade" = mean(Exam, na.rm = TRUE)) |>
  knitr::kable()
```

## Question 3
```{r}
n_abs <- grades |> 
 summarise(n = sum(is.na(Exam)))
```
The number of students who did not take the exam is `r n_abs[1,1]`.


## Question 4
```{r}
grades |> 
  ggplot(aes(x = Exam)) +
  geom_bar(na.rm = TRUE)
```


## Question 5
```{r}
grades |>
  group_by(Group) |>
  summarise("number of students" = n()) |>
  knitr::kable()
```


## Quesiton 6
```{r}
grades |> 
  ggplot(aes(y = Group)) +
  geom_bar()
```

# Question 7
```{r}
grades |>
  ggplot(aes(y = Group, fill = as.factor(Exam))) +
  geom_bar(position = "fill") +
  scale_fill_discrete(name = "Exam grade")
```


```{r warning=FALSE}
grades |>
  ggplot(aes(y = Exam)) +
  geom_bar() +
  facet_wrap(~Group)
```
# Question 8

```{r}
n_abs1 <- grades |>
  group_by(Group) |>
  summarise("number of absent students" = sum(is.na(Exam)))

n_abs1
```

# Question 9

```{r}
n_abs |> 
  ggplot(aes(y = Group, x = `number of absent students`)) +
  geom_col()
```

# Question 10
```{r}
long <- grades |>
  pivot_longer(col = c("Exam", starts_with("MCQ"), starts_with("Online_MCQ")), names_to = "name", values_to = "value") 
```

# Question 11
```{r}
n_missing_grade <- long |>
  group_by(Id) |>
  summarise("number of absent grades" = sum(is.na(value)))

n_missing_grade
```

# Question 12
```{r}
n_missing_grade |> ggplot(aes(y = `number of absent grades`)) +
  geom_bar()
```


# Question 13
```{r}
n_abs2 <- long |> 
  filter(name == "Exam") |>
  group_by(Group) |>
  summarise("number of absent students" = sum(is.na(value)))

n_abs2
```


# Question 14
```{r}
n_missing_online_tests <- long |>
  filter(str_starts(name, "Online_MCQ")) |>
  group_by(Id) |>
  summarise("number of missing online tests" = sum(is.na(value)))
```


# Question 15
```{r}
inner_join(grades, n_missing_online_tests, by = "Id") |>
  ggplot(aes(y = `number of missing online tests`, fill = Exam)) +
  geom_bar(na.rm=TRUE)
```

# Question 16
```{r}
two_col_table1 <- long |>
  filter(str_starts(name, "MCQ"))|>
  group_by(Id) |>
  summarise("Missed"= (sum(is.na(value)) > 0))
```

# Question 17
```{r}
two_col_table2 <- long |>
  filter(str_starts(name, "MCQ"))|> 
  group_by(Group, Id) |> 
  summarise("Missed" = (sum(is.na(value)) > 0)) |> 
  summarise("P_missed" = sum(Missed) / n())
```
# Question 18
```{r}
  grades |> 
  group_by(Group) |>
  summarise("Average grade" = mean(Exam, na.rm = TRUE)) |>
  inner_join(two_col_table2, by = "Group")  |>
  ggplot(aes(x = P_missed, y = `Average grade`)) +
  geom_line()
```

